name: 'My Docker Action'
description: 'A custom action that runs inside a Docker container.'
author: 'Akshaya M'
inputs:
  input1:
    description: 'First input'
    required: true
    default: 'Hello'
  input2:
    description: 'Second input'
    required: true
    default: 'World'
outputs:
  result:
    description: 'The combined result of the inputs'
runs:
  using: 'docker'
  image: 'Dockerfile'  # Uses the Dockerfile in the repository
  args:
    - input1=${{ inputs.input1 }}
    - input2=${{ inputs.input2 }}
