name: Docker Action Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: docker build -t my-docker-action .

      - name: Check Docker build status
        run: docker images

      - name: Run Docker action with environment variables
        id: run-my-docker-action
        uses: ./
        
